###############################################################################
#                             APPLICATION CONFIG                              #
###############################################################################

# Development options
# debug: true

spring:
  # AOP
  aop:
    proxy-target-class: false
    

# JWT
security:
  jwt:
    secret:
      exposure: 1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890