version: '3'
services:
  jwt-db:
    image: postgres:15.0-alpine
    environment:
      PGUSER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - db
  jwt-ws:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      jwt-db:
        condition: service_healthy
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 60s
    environment:
      # JDBC
      - spring.datasource.url=jdbc:postgresql://jwt-db:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=password
    volumes:
      - jwt-logs:/app/logs
    networks:
      - db
volumes:
  jwt-logs:
networks:
  db:
